version: 0.2

env:
  variables:
    BUILD_DIR: "."
    S3_BUCKET: "msis-4363"   # your bucket name

phases:
  install:
    commands:
      - echo "No dependencies needed"
  build:
    commands:
      - echo "No build step"
  post_build:
    commands:
      - echo "Deploying to S3"
      - aws s3 sync $BUILD_DIR s3://$S3_BUCKET --delete --exclude ".git/*" --exclude "buildspec.yml"

artifacts:
  files:
    - '**/*'
  base-directory: $BUILD_DIR
